# charts/helm01_micro/Chart.yaml
apiVersion: v2
name: market-app
description: market app helm chart for kuber
type: application
version: 0.1.0        # helm chart 자체 버전 (따옴표 안씀)
apiVersion: "1.0.0"   # chart 로 배포하는 app의 버전